name: map_elevation
description: A widget to display elevation of a track (polyline) like Leaflet.Elevation.
version: 2.0.0
homepage: https://github.com/OwnWeb/map_elevation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
